language: node_js
node_js:
  - "4"
  
jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    organization: "adlerosn-github"
    token: $SONAR_TOKEN
   
before_script:
    - cd pmdsys
    - npm install
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g karma
    - npm install -g typescript
    - npm install -g tsd

script: 
  - npm test
  - cd ..
  - sonar-scanner

notifications:
  slack: 