language: node_js
node_js:
  - "4"
  
jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    organization: "adlerosn-github"
    token: $SONAR_TOKEN
   
before_script:
    - cd pmdsys
    - npm install
    - ionic serve
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script: 
  - npm test
  - ionic serve
  - cd ..
  - sonar-scanner

notifications:
  slack: 
