language: node_js
node_js:
  - "4"
  
jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    organization: "adlerosn-github"
    token: $SONAR_TOKEN
   
before_script:
    - cd PASTA_PROJETO
    - npm install
    - npm install -g cordova
    - npm install -g ionic
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script: 
  - npm test
  - cd ../pmdsys
  - ionic build browser --prod
  - cd ..
  - sonar-scanner


notifications:
  slack: 